language: node_js
node_js:
    - 10
script: yarn lint && yarn install && yarn build
deploy:
    provider: npm
    email: ackeedevelopment@gmail.com
    skip_cleanup: true
    api_key:
        secure: w/KgNOsYshcfDsUyLlXzaOD04PRYmAQWIGXfePQCxQwsIPCSHNvRz4SJKZ2CKPkdUUlc9mbveSy6rQkWFnL7uGYBnFjGmGFXFTJv7yQ46iVzMcJ85H5J7vNGb7cE/tQHZfViTpgYxtdgIu4bOlbJqb5Yf1fQPaibHBypkQHYW5T5YXQ3bMalLbyXSvQhEdDGiI1+0NNJjT2ibYvK9obct2Y4y3MDCJpP4HThE+VQQyWHz2Ue1araNV1E4UNdtGST2vCAHsdClSlzW7TpifEzn9xm5bxrXDOOM/e8xOVLXdYB7Acc2n6+zOl7hkANPkA97E1/CcXXLB0gJc9tAML0omFM4eABnTdr0//VfVN8knU9+Pw71WT+L3h4h8833TwCgNCZ3Y/l3wmlvsAXC+i2SQV8cFacjO6d5608+awMuyrTDYVphxdskLjYD2gw3Bkcra9SPNLxDXD6pyecTaRBiueGSMCLQMTIFfZOoN18BsEDqRmCmm++Omd7HXEnc/Sg6sRyIk14vwVie21kHgWtGNRMqlVTp3NjNnTnKxyk59FRte0YickfdezXNGNvMEX4eUtWG59e/9dAetv1AWElIc7bxMuTSDabCfQRY6Z1bozcz+6BuXfWg2e0IlO0iylj/tRdve9x1W0DqdmiCpedK3ITbAiRqWLVCuQaW4njM+Y=
    on:
        tags: true
        repo: AckeeCZ/petrus
