export const AUTH_LOGIN = '@@petrus/AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = '@@petrus/AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = '@@petrus/AUTH_LOGIN_FAILURE';

export const AUTH_LOGOUT = '@@petrus/AUTH_LOGOUT';

export const SET_AUTH_TOKENS = '@@petrus/SET_AUTH_TOKENS';

export const AUTH_REFRESH_TOKEN = '@@petrus/AUTH_REFRESH_TOKEN';
export const AUTH_REFRESH_TOKEN_SUCCESS = '@@petrus/AUTH_REFRESH_TOKEN_SUCCESS';
export const AUTH_REFRESH_TOKEN_FAILURE = '@@petrus/AUTH_REFRESH_TOKEN_FAILURE';
export const PROCESS_TOKEN_REFRESH = '@@petrus/PROCESS_TOKEN_REFRESH';

export const FETCH_AUTH_USER_REQUEST = '@@petrus/FETCH_AUTH_USER_REQUEST';
export const FETCH_AUTH_USER_SUCCESS = '@@petrus/FETCH_AUTH_USER_SUCCESS';
export const FETCH_AUTH_USER_FAILURE = '@@petrus/FETCH_AUTH_USER_FAILURE';

export const ACCESS_TOKEN_AVAILABLE = '@@petrus/ACCESS_TOKEN_AVAILABLE';
export const ACCESS_TOKEN_UNAVAILABLE = '@@petrus/ACCESS_TOKEN_UNAVAILABLE';

export const AUTH_SESSION_START = '@@petrus/AUTH_SESSION_START';
export const AUTH_SESSION_END = '@@petrus/AUTH_SESSION_END';
export const AUTH_SESSION_PAUSE = '@@petrus/AUTH_SESSION_PAUSE';
export const AUTH_SESSION_RESUME = '@@petrus/AUTH_SESSION_RESUME';

export const SET_TOKENS_PERSISTENCE = '@@petrus/SET_TOKENS_PERSISTENCE';

export const SET_USER_WITH_TOKENS = '@@petrus/SET_USER_WITH_TOKENS';

export const RETRIEVE_TOKENS_REQUEST = '@@petrus/RETRIEVE_TOKENS_REQUEST';
export const RETRIEVE_TOKENS_RESOLVE = '@@petrus/RETRIEVE_TOKENS_RESOLVE';
