const statusTypes = {
    ACCESS_TOKEN_AVAILABLE: 'ACCESS_TOKEN_AVAILABLE',
    ACCESS_TOKEN_UNAVAILABLE: 'ACCESS_TOKEN_UNAVAILABLE',

    AUTH_SESSION_START: 'AUTH_SESSION_START',
    AUTH_SESSION_END: 'AUTH_SESSION_END',
    AUTH_SESSION_PAUSE: 'AUTH_SESSION_PAUSE',
    AUTH_SESSION_RESUME: 'AUTH_SESSION_RESUME',
};

export default statusTypes;
